### PR TITLE
add spf macro expansion for ipv6 addresses

### PR DESCRIPTION
**Pull request by jimmystewpot**
Hello,

Thank you for creating a very usable SPF library.

We have found that there is a bug where you do not handle IPv6 macro's. I have expanded on the IPv4 capability to add the expansion of IPv6 out to full dotted format. This is useful for %{ir} macros with IPv6. In this use case we need to turn the compressed ipv6 format into the full dotted format address. When the address is resolved it is done so with an IN A lookup.

### CODE REVIEW

**Comment by albertito** [comment]
Thanks for finding the bug, and for the patch!

I've merged it into the `next` branch, with a couple of changes: I expanded the commit message, moved the printing logic to a separate function (just for readability), and also made it remove the extra "." (which shouldn't matter much in most cases for DNS resolution, but it could cause trouble).

The result is commit 4652e474.

Can you take a look and let me know if it looks ok to you? If so, I'll leave it in `next` for a few days just in case, and then merge it into `master`, as usual.

Thanks again!

**Comment by albertito** [comment]
Make that commit affd20d :)

I changed the int literal `0b1111` to `0xf` for compatibility with Go 1.11 (which is the oldest version supported at the moment).

**Comment by jimmystewpot** [comment]
Ok, thanks appreciate the feedback and it makes sense to bring out the expansion into its own function, allows for testing etc specifically.

**Comment by albertito** [comment]
Closing the PR since the change is already merged in `master` (commit c059c43277f6497118733725fb8c352b7085c78b).

Thank you!

**Pull request closed without merging**
